lcr-modules:
    
    lymphgen_subtyping:

        # TODO: Update the list of available wildcards, if applicable
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            by_sample: "results/direct_out_tables-1.0/99-outputs/{seq_type}--{genome_build}/by_sample.csv"
            by_mutation: "results/direct_out_tables-1.0/99-outputs/{seq_type}--{genome_build}/by_mutation.csv"
            by_sv_samples: "results/direct_out_tables-1.0/99-outputs/{seq_type}--{genome_build}/by_sv_sample.csv"

        scratch_subdirectories: []

        scripts:
            sample_annotation_file: "{MODSDIR}/etc/R/sample_annotation_file.R"
            mutation_flat_file: "{MODSDIR}/etc/R/mutation_flat_file.R"
            

        conda_envs:
            postprocessing: "{MODSDIR}/envs/postprocessing-1.0.yaml"
            
            
        threads:
            step_1: 4

        resources:
            step_1: 
                mem_mb: 2000
            
        pairing_config:
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: null
                run_paired_tumours_as_unpaired: False
