lcr-modules:
    
    strelka:
        inputs:
            # Available wildcards: {seq_type} {genome_build} {sample_id}
            sample_bam: "__UPDATE__"
            sample_bai: "__UPDATE__"
            
            # Available wildcards: {seq_type} {genome_build} {tumour_id} {normal_id} {pair_status}
            # Set these values to `null` (no quotes) or "" if you don't have these files
            candidate_small_indels: "__UPDATE__"

        scratch_subdirectories: []

        options:
            configure:
                _default: ""
                mrna: "--rna"
                capture: "--exome"
            strelka: "-m local"

        conda_envs:
            strelka: "{MODSDIR}/envs/strelka-2.9.10.yaml"
            tabix: "{MODSDIR}/envs/tabix-0.2.6.yaml"
            bcftools: "{MODSDIR}/envs/bcftools-1.9.yaml"
            
        threads:
            strelka: 30 #if you increase this the mem_mb should also be increased, probably proportionately

        resources:
            strelka_run: 
                mem_mb: 4000
        
        mem_mb:
            bcftools_sort: 20000

        pairing_config:
            genome:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
            capture:
                run_paired_tumours: True
                run_unpaired_tumours_with: "unmatched_normal"
                run_paired_tumours_as_unpaired: False
